// Action types
const FETCH_SEATS_SUCCESS = 'FETCH_SEATS_SUCCESS';
const SET_NUM_OF_SEATS = 'SET_NUM_OF_SEATS';
const SET_LOADING = 'SET_LOADING';
const RESERVE_SEATS_REQUEST = 'RESERVE_SEATS_REQUEST';
const RESERVE_SEATS_SUCCESS = 'RESERVE_SEATS_SUCCESS';
const RESET_ALL_SEATS = 'RESET_ALL_SEATS';

export{
    FETCH_SEATS_SUCCESS,
    SET_NUM_OF_SEATS,
    SET_LOADING,
    RESERVE_SEATS_REQUEST,
    RESERVE_SEATS_SUCCESS,
    RESET_ALL_SEATS

}